import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid, BarChart, Bar, PieChart, Pie, Cell } from 'recharts';
import React, { useMemo, useState } from 'react';
export const COLORS=['#2563eb','#16a34a','#f97316','#dc2626','#7c3aed','#0891b2','#f59e0b'];
export const money=(n:number,currency='')=>`${currency}${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
export const pct=(n:number)=>`${(Number(n||0)*100).toFixed(2)}%`;
export function Loading({show}:{show:boolean}){return show?<div className="card animate-pulse text-blue-700">資料載入中...</div>:null}
export function ErrorBox({msg}:{msg?:string}){return msg?<div className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-amber-800">{msg}</div>:null}
export function Stat({label,value}:{label:string,value:any}){return <div className="card"><div className="muted">{label}</div><div className="mt-1 text-xl font-bold">{value}</div></div>}
export function TextInput({label,value,onChange,type='text'}:{label:string,value:any,onChange:(v:any)=>void,type?:string}){return <label className="block"><span className="label">{label}</span><input className="input mt-1" type={type} value={value} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)}/></label>}
export function SelectInput({label,value,onChange,options}:{label:string,value:any,onChange:(v:any)=>void,options:string[]}){return <label className="block"><span className="label">{label}</span><select className="input mt-1" value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
export function LineBox({data,x='date',lines,title}:{data:any[],x?:string,lines:string[],title:string}){return <div className="card"><h3 className="font-bold mb-3">{title}</h3><div className="h-72"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey={x}/><YAxis/><Tooltip formatter={(v:any)=>money(Number(v))}/>{lines.map((l,i)=><Line key={l} type="monotone" dot={false} dataKey={l} stroke={COLORS[i%COLORS.length]}/>)}</LineChart></ResponsiveContainer></div></div>}
export function BarBox({data,x,bar,title}:{data:any[],x:string,bar:string,title:string}){return <div className="card"><h3 className="font-bold mb-3">{title}</h3><div className="h-72"><ResponsiveContainer><BarChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey={x}/><YAxis/><Tooltip/><Bar dataKey={bar} fill="#2563eb"/></BarChart></ResponsiveContainer></div></div>}
export function PieBox({data,nameKey,valueKey,title}:{data:any[],nameKey:string,valueKey:string,title:string}){return <div className="card"><h3 className="font-bold mb-3">{title}</h3><div className="h-72"><ResponsiveContainer><PieChart><Pie data={data} dataKey={valueKey} nameKey={nameKey} label>{data.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div></div>}
export function SortTable({data,title}:{data:any[],title:string}){const [key,setKey]=useState(''); const rows=useMemo(()=>{if(!key)return data||[]; return [...(data||[])].sort((a,b)=>String(a[key]).localeCompare(String(b[key]),undefined,{numeric:true}))},[data,key]); const cols=rows[0]?Object.keys(rows[0]):[]; return <div className="card overflow-auto"><h3 className="font-bold mb-3">{title}</h3>{rows.length===0?<p className="muted">尚無資料</p>:<table className="min-w-full text-sm"><thead><tr>{cols.map(c=><th className="p-2 text-left border-b" onClick={()=>setKey(c)} key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(0,200).map((r,i)=><tr key={i} className="odd:bg-slate-50">{cols.map(c=><td className="p-2 border-b" key={c}>{typeof r[c]==='number'?money(r[c]):String(r[c])}</td>)}</tr>)}</tbody></table>}</div>}
